module Directories
  class Categories

    def list

      {
        "area" => [
            "administrative_area_level_1",
            "administrative_area_level_2",
            "administrative_area_level_3",
            "administrative_area_level_4",
            "administrative_area_level_5",
            "Border Crossing",
            "City",
            "colloquial_area",
            "Country",
            "country",
            "County",
            "Farm",
            "Forest",
            "Island",
            "Lake",
            "locality",
            "Neighborhood",
            "neighborhood",
            "Park",
            "Pedestrian Plaza",
            "Plaza",
            "political",
            "postal_code",
            "postal_town",
            "premise",
            "River",
            "Road",
            "route",
            "State",
            "States & Municipalities",
            "Street",
            "sublocality",
            "sublocality_level_1",
            "sublocality_level_2",
            "sublocality_level_3",
            "sublocality_level_4",
            "sublocality_level_5",
            "Town",
            "Village",
            "Vineyard",
            "Volcano",
        ],

        "do" => [
            "amusement_park",
            "Arcade",
            "Badminton Court",
            "Baseball Field",
            "Baseball Stadium",
            "Basketball Court",
            "Basketball Stadium",
            "Bowling Alley",
            "Bowling Green",
            "bowling_alley",
            "Boxing Gym",
            "Casino",
            "casino",
            "Circus",
            "Circus School",
            "Climbing Gym",
            "Comedy Club",
            "Concert Hall",
            "Conference",
            "Cycle Studio",
            "Dance Studio",
            "Disc Golf",
            "Dive Shop",
            "Dive Spot",
            "Dog Run",
            "Event",
            "Fair",
            "Festival",
            "Fishing Spot",
            "Football Stadium",
            "Gaming Cafe",
            "General Entertainment",
            "Go Kart Track",
            "Golf Course",
            "Gun Range",
            "Gym",
            "gym",
            "Gym / Fitness Center",
            "Gym Pool",
            "Gymnastics Gym",
            "Harbor / Marina",
            "Hockey Arena",
            "Hockey Field",
            "Hookah Bar",
            "Indie Movie Theater",
            "Indie Theater",
            "Jazz Club",
            "Laser Tag",
            "Martial Arts Dojo",
            "Mini Golf",
            "Movie Theater",
            "movie_theater",
            "Multiplex",
            "Music Festival",
            "Music Venue",
            "Opera House",
            "Other Event",
            "Other Great Outdoors",
            "Outdoors & Recreation",
            "Paintball Field",
            "Performing Arts Venue",
            "Planetarium",
            "Pool Hall",
            "Racetrack",
            "Rafting",
            "Recreation Center",
            "Rock Climbing Spot",
            "Rock Club",
            "Roller Rink",
            "Rugby Pitch",
            "Salsa Club",
            "Skate Park",
            "Skating Rink",
            "Ski Area",
            "Ski Chairlift",
            "Ski Trail",
            "Soccer Field",
            "Soccer Stadium",
            "Social Club",
            "Sports Club",
            "Squash Court",
            "Stables",
            "Stadium",
            "stadium",
            "Street Fair",
            "Summer Camp",
            "Surf Spot",
            "Swim School",
            "Tennis",
            "Tennis Court",
            "Theater",
            "Theme Park",
            "Theme Park Ride / Attraction",
            "Track",
            "Track Stadium",
            "Trail",
            "Volleyball Court",
            "Water Park",
            "Yoga Studio",
        ],

        "drink" => [
            "Apres Ski Bar",
            "Bar",
            "bar",
            "Beach Bar",
            "Beer Garden",
            "Beer Store",
            "Brewery",
            "Champagne Bar",
            "Cocktail Bar",
            "Distillery",
            "Dive Bar",
            "Gay Bar",
            "Hotel Bar",
            "Irish Pub",
            "Karaoke Bar",
            "Liquor Store",
            "liquor_store",
            "Lounge",
            "night_club",
            "Nightclub",
            "Nightlife Spot",
            "Other Nightlife",
            "Piano Bar",
            "Pub",
            "Sake Bar",
            "Speakeasy",
            "Sports Bar",
            "Strip Club",
            "Whisky Bar",
            "Wine Bar",
            "Wine Shop",
            "Winery",
        ],

        "food" => [
            "Acai House",
            "Acehnese Restaurant",
            "Afghan Restaurant",
            "African Restaurant",
            "Airport Food Court",
            "American Restaurant",
            "Andhra Restaurant",
            "Anhui Restaurant",
            "Arepa Restaurant",
            "Argentinian Restaurant",
            "Asian Restaurant",
            "Australian Restaurant",
            "Austrian Restaurant",
            "Awadhi Restaurant",
            "Bagel Shop",
            "Baiano Restaurant",
            "Bakery",
            "bakery",
            "Balinese Restaurant",
            "BBQ Joint",
            "Beijing Restaurant",
            "Belarusian Restaurant",
            "Belgian Restaurant",
            "Bengali Restaurant",
            "Betawinese Restaurant",
            "Bistro",
            "Blini House",
            "Borek Place",
            "Bougatsa Shop",
            "Brasseries",
            "Brasserie",
            "Brazilian Restaurant",
            "Breakfast Spot",
            "Bubble Tea Shop",
            "Buffet",
            "Burger Joint",
            "Burrito Place",
            "Butcher",
            "cafe",
            "Café",
            "Cafeteria",
            "Cajun / Creole Restaurant",
            "Cambodian Restaurant",
            "Candy Store",
            "Cantonese Restaurant",
            "Caribbean Restaurant",
            "Caucasian Restaurant",
            "Central Brazilian Restaurant",
            "Chaat Place",
            "Cheese Shop",
            "Chettinad Restaurant",
            "Chinese Aristocrat Restaurant",
            "Chinese Breakfast Place",
            "Chinese Restaurant",
            "Chocolate Shop",
            "Churrascaria",
            "Cigkofte Place",
            "Coffee Shop",
            "College Cafeteria",
            "Comfort Food Restaurant",
            "Creperie",
            "Cretan Restaurant",
            "Cuban Restaurant",
            "Cupcake Shop",
            "Czech Restaurant",
            "Deli / Bodega",
            "Dessert Shop",
            "Dhaba",
            "Dim Sum Restaurant",
            "Diner",
            "Doner Restaurant",
            "Dongbei Restaurant",
            "Donut Shop",
            "Dosa Place",
            "Dumpling Restaurant",
            "Eastern European Restaurant",
            "Empada House",
            "Empanada Restaurant",
            "English Restaurant",
            "Ethiopian Restaurant",
            "Falafel Restaurant",
            "Farmers Market",
            "Fast Food Restaurant",
            "Filipino Restaurant",
            "Fish & Chips Shop",
            "Fish Market",
            "Fish Taverna",
            "Fondue Restaurant",
            "Food",
            "food",
            "Food & Drink Shop",
            "Food Court",
            "Food Truck",
            "French Restaurant",
            "Fried Chicken Joint",
            "Frozen Yogurt",
            "Fruit & Vegetable Store",
            "Fujian Restaurant",
            "Gastropub",
            "German Restaurant",
            "Gluten-free Restaurant",
            "Goan Restaurant",
            "Goiano Restaurant",
            "Gourmet Shop",
            "Gozleme Place",
            "Greek Restaurant",
            "Grilled Meat Restaurant",
            "Grocery Store",
            "grocery_or_supermarket",
            "Guizhou Restaurant",
            "Gujarati Restaurant",
            "Hainan Restaurant",
            "Hakka Restaurant",
            "Halal Restaurant",
            "Hawaiian Restaurant",
            "Health Food Store",
            "Henan Restaurant",
            "Himalayan Restaurant",
            "Home Cooking Restaurant",
            "Hong Kong Restaurant",
            "Hot Dog Joint",
            "Hotpot Restaurant",
            "Huaiyang Restaurant",
            "Hubei Restaurant",
            "Hunan Restaurant",
            "Hungarian Restaurant",
            "Hyderabadi Restaurant",
            "Ice Cream Shop",
            "Imperial Restaurant",
            "Indian Chinese Restaurant",
            "Indian Restaurant",
            "Indonesian Restaurant",
            "Irani Cafe",
            "Italian Restaurant",
            "Jain Restaurant",
            "Japanese Restaurant",
            "Javanese Restaurant",
            "Jewish Restaurant",
            "Jiangsu Restaurant",
            "Jiangxi Restaurant",
            "Juice Bar",
            "Kafenio",
            "Karnataka Restaurant",
            "Kebab Restaurant",
            "Kerala Restaurant",
            "Kofte Place",
            "Kokoreç Restaurant",
            "Korean Restaurant",
            "Kosher Restaurant",
            "Latin American Restaurant",
            "Mac & Cheese Joint",
            "Macanese Restaurant",
            "Magirio",
            "Maharashtrian Restaurant",
            "Malaysian Restaurant",
            "Manadonese Restaurant",
            "Manchu Restaurant",
            "Manti Place",
            "meal_delivery",
            "meal_takeaway",
            "Meatball Place",
            "Mediterranean Restaurant",
            "Mexican Restaurant",
            "Meyhane",
            "Meze Restaurant",
            "Middle Eastern Restaurant",
            "Mineiro Restaurant",
            "Modern European Restaurant",
            "Modern Greek Restaurant",
            "Molecular Gastronomy Restaurant",
            "Mongolian Restaurant",
            "Moroccan Restaurant",
            "Mughlai Restaurant",
            "Multicuisine Indian Restaurant",
            "New American Restaurant",
            "North Indian Restaurant",
            "Northeast Indian Restaurant",
            "Northeastern Brazilian Restaurant",
            "Northern Brazilian Restaurant",
            "Organic Grocery",
            "Ouzeri",
            "Padangnese Restaurant",
            "Paella Restaurant",
            "Pakistani Restaurant",
            "Parsi Restaurant",
            "Pastelaria",
            "Patsa Restaurant",
            "Peking Duck Restaurant",
            "Pelmeni House",
            "Persian Restaurant",
            "Peruvian Restaurant",
            "Pide Place",
            "Pie Shop",
            "Pizza Place",
            "Polish Restaurant",
            "Portuguese Restaurant",
            "Punjabi Restaurant",
            "Rajasthani Restaurant",
            "Ramen / Noodle House",
            "Restaurant",
            "restaurant",
            "Romanian Restaurant",
            "Russian Restaurant",
            "Salad Place",
            "Sandwich Place",
            "Scandinavian Restaurant",
            "Seafood Restaurant",
            "Shaanxi Restaurant",
            "Shandong Restaurant",
            "Shanghai Restaurant",
            "Shanxi Restaurant",
            "Smoothie Shop",
            "Snack Place",
            "Soup Place",
            "South American Restaurant",
            "South Indian Restaurant",
            "Southeastern Brazilian Restaurant",
            "Southern / Soul Food Restaurant",
            "Southern Brazilian Restaurant",
            "Souvlaki Shop",
            "Spanish Restaurant",
            "Sri Lankan Restaurant",
            "Steakhouse",
            "Street Food Gathering",
            "Sundanese Restaurant",
            "Supermarket",
            "Sushi Restaurant",
            "Sweet Shop",
            "Swiss Restaurant",
            "Szechuan Restaurant",
            "Taco Place",
            "Taiwanese Restaurant",
            "Tapas Restaurant",
            "Tapiocaria",
            "Tatar Restaurant",
            "Taverna",
            "Tea Room",
            "Thai Restaurant",
            "Tianjin Restaurant",
            "Tibetan Restaurant",
            "Tsipouro Restaurant",
            "Turkish Restaurant",
            "Udupi Restaurant",
            "Ukrainian Restaurant",
            "Varenyky restaurant",
            "Vegetarian / Vegan Restaurant",
            "Vietnamese Restaurant",
            "West-Ukrainian Restaurant",
            "Wings Joint",
            "Xinjiang Restaurant",
            "Yunnan Restaurant",
            "Zhejiang Restaurant",
        ],

        "help" => [
            "Acupuncturist",
            "Alternative Healer",
            "doctor",
            "Doctor's Office",
            "Drugstore / Pharmacy",
            "embassy",
            "Embassy / Consulate",
            "Emergency Room",
            "Eye Doctor",
            "health",
            "Hospital",
            "hospital",
            "Medical Center",
            "Medical School",
            "Mental Health Office",
            "pharmacy",
            "physiotherapist",
            "Tourist Information Center",
            "Travel Agency",
            "Veterinarian",
            "veterinary_care",
        ],

        "money" => [
            "ATM",
            "atm",
            "Bank",
            "bank",
            "Check Cashing Service",
            "finance",
        ],

        "other" => [
            "accounting",
            "Advertising Agency",
            "Animal Shelter",
            "Assisted Living",
            "Astrologer",
            "Athletics & Sports",
            "Auditorium",
            "beauty_salon",
            "Betting Shop",
            "Business Service",
            "Campaign Office",
            "Car Dealership",
            "Car Wash",
            "car_dealer",
            "car_wash",
            "Chiropractor",
            "Club House",
            "College Academic Building",
            "College Administrative Building",
            "College Arts Building",
            "College Auditorium",
            "College Baseball Diamond",
            "College Basketball Court",
            "College Classroom",
            "College Communications Building",
            "College Cricket Pitch",
            "College Engineering Building",
            "College Football Field",
            "College Gym",
            "College History Building",
            "College Hockey Rink",
            "College Lab",
            "College Library",
            "College Math Building",
            "College Quad",
            "College Rec Center",
            "College Residence Hall",
            "College Science Building",
            "College Soccer Field",
            "College Stadium",
            "College Technology Building",
            "College Tennis Court",
            "College Theater",
            "College Track",
            "Community Center",
            "Community College",
            "Conference Room",
            "Construction & Landscaping",
            "Convenience Store",
            "convenience_store",
            "Convention",
            "Convention Center",
            "Coworking Space",
            "Credit Union",
            "Cricket Ground",
            "Daycare",
            "dentist",
            "Dentist's Office",
            "Design Studio",
            "Distribution Center",
            "Driving School",
            "Dry Cleaner",
            "electrician",
            "Elementary School",
            "establishment",
            "Event Service",
            "Event Space",
            "Factory",
            "Field",
            "Financial or Legal Service",
            "Fire Station",
            "fire_station",
            "Fireworks Store",
            "Flight School",
            "Fraternity House",
            "Funeral Home",
            "funeral_home",
            "General Travel",
            "general_contractor",
            "geocode",
            "hair_care",
            "Hardware Store",
            "hardware_store",
            "Health & Beauty Service",
            "High School",
            "Home Service",
            "Housing Development",
            "insurance_agency",
            "Internet Cafe",
            "Intersection",
            "IT Services",
            "Laboratory",
            "Language School",
            "Laundromat",
            "laundry",
            "Laundry Service",
            "Law School",
            "Lawyer",
            "lawyer",
            "Locksmith",
            "locksmith",
            "Lottery Retailer",
            "Marijuana Dispensary",
            "Meeting Room",
            "Middle School",
            "Military Base",
            "movie_rental",
            "Moving Target",
            "moving_company",
            "Music School",
            "Nail Salon",
            "Newsstand",
            "Non-Profit",
            "Nursery School",
            "Office",
            "Other Repair Shop",
            "painter",
            "Pet Service",
            "Pet Store",
            "Photography Lab",
            "Piercing Parlor",
            "plumber",
            "police",
            "Police Station",
            "post_box",
            "Prayer Room",
            "Preschool",
            "Private School",
            "Professional & Other Places",
            "Radio Station",
            "Real Estate Office",
            "real_estate_agency",
            "Recording Studio",
            "Recruiting Agency",
            "Recycling Facility",
            "Religious School",
            "roofing_contractor",
            "Salon / Barbershop",
            "Shipping Store",
            "Shoe Repair",
            "Shop & Service",
            "Sorority House",
            "storage",
            "Storage Facility",
            "Student Center",
            "subpremise",
            "Tanning Salon",
            "Tattoo Parlor",
            "Tech Startup",
            "Trade School",
            "travel_agency",
            "TV Station",
            "University",
            "university",
            "Voting Booth",
            "Warehouse",
        ],

        "relax" => [
            "Airport Lounge",
            "Bath House",
            "Bathing Area",
            "Beach",
            "Hot Spring",
            "Hotel Pool",
            "Massage Studio",
            "Nudist Beach",
            "Playground",
            "Pool",
            "Rest Area",
            "Roof Deck",
            "Spa",
            "spa",
            "Travel Lounge",
        ],

        "see" => [
            "Aquarium",
            "aquarium",
            "Art Gallery",
            "Art Museum",
            "art_gallery",
            "Arts & Entertainment",
            "Botanical Garden",
            "Bridge",
            "Buddhist Temple",
            "Building",
            "Capitol Building",
            "Castle",
            "Cemetery",
            "cemetery",
            "Church",
            "church",
            "City Hall",
            "city_hall",
            "College & University",
            "Courthouse",
            "courthouse",
            "Cultural Center",
            "department_store",
            "Garden",
            "General College & University",
            "Government Building",
            "Hindu Temple",
            "hindu_temple",
            "Historic Site",
            "History Museum",
            "intersection",
            "Library",
            "library",
            "Lighthouse",
            "local_government_office",
            "Monastery",
            "Monument / Landmark",
            "Mosque",
            "mosque",
            "Mountain",
            "Museum",
            "museum",
            "National Park",
            "natural_feature",
            "Nature Preserve",
            "Outdoor Sculpture",
            "Palace",
            "Parade",
            "park",
            "place_of_worship",
            "point_of_interest",
            "Post Office",
            "post_office",
            "Prison",
            "Scenic Lookout",
            "School",
            "school",
            "Science Museum",
            "Sculpture Garden",
            "Shrine",
            "Spiritual Center",
            "Street Art",
            "Synagogue",
            "synagogue",
            "Temple",
            "Town Hall",
            "Tree",
            "Well",
            "Zoo",
            "zoo",
        ],

        "shop" => [
            "Accessories Store",
            "Adult Boutique",
            "Antique Shop",
            "Arts & Crafts Store",
            "Baby Store",
            "bicycle_store",
            "Big Box Store",
            "Bike Shop",
            "Board Shop",
            "book_store",
            "Bookstore",
            "Boutique",
            "Bridal Shop",
            "Camera Store",
            "Carpet Store",
            "Christmas Market",
            "Clothing Store",
            "clothing_store",
            "College Bookstore",
            "Comic Shop",
            "Cosmetics Shop",
            "Costume Shop",
            "Department Store",
            "Discount Store",
            "Electronics Store",
            "electronics_store",
            "Fabric Shop",
            "Fishing Store",
            "Flea Market",
            "florist",
            "Flower Shop",
            "Frame Store",
            "Furniture / Home Store",
            "furniture_store",
            "Garden Center",
            "Gift Shop",
            "Gun Shop",
            "Herbs & Spices Store",
            "Hobby Shop",
            "home_goods_store",
            "Hunting Supply",
            "Jewelry Store",
            "jewelry_store",
            "Kids Store",
            "Knitting Store",
            "Leather Goods Store",
            "Lingerie Store",
            "Luggage Store",
            "Mall",
            "Market",
            "Mattress Store",
            "Men's Store",
            "Miscellaneous Shop",
            "Mobile Phone Shop",
            "Motorcycle Shop",
            "Music Store",
            "Night Market",
            "Optical Shop",
            "Outdoor Supply Store",
            "Outlet Store",
            "Paper / Office Supplies Store",
            "Pawn Shop",
            "Perfume Shop",
            "pet_store",
            "Pop-Up Shop",
            "Print Shop",
            "Record Shop",
            "Shoe Store",
            "shoe_store",
            "shopping_mall",
            "Smoke Shop",
            "Souvenir Shop",
            "Sporting Goods Shop",
            "Stationery Store",
            "Stoop Sale",
            "store",
            "Tailor Shop",
            "Thrift / Vintage Store",
            "Toy / Game Store",
            "Used Bookstore",
            "Video Game Store",
            "Video Store",
            "Warehouse Store",
            "Watch Repair Shop",
            "Women's Store",
        ],

        "stay" => [
            "Bed & Breakfast",
            "Boarding House",
            "Campground",
            "campground",
            "Home (private)",
            "Home",
            "Hostel",
            "Hotel",
            "lodging",
            "Motel",
            "Residence",
            "Residential Building (Apartment / Condo)",
            "Resort",
            "RV Park",
            "rv_park",
            "Ski Chalet",
            "Ski Lodge",
            "Trailer Park",
        ],

        "transit" => [
            "Airport",
            "airport",
            "Airport Gate",
            "Airport Terminal",
            "Airport Tram",
            "Auto Garage",
            "Automotive Shop",
            "Bike Rental / Bike Share",
            "Boat or Ferry",
            "Bus Line",
            "Bus Station",
            "Bus Stop",
            "bus_station",
            "Cable Car",
            "car_rental",
            "car_repair",
            "Country Dance Club",
            "EV Charging Station",
            "Gas Station / Garage",
            "gas_station",
            "Light Rail",
            "Parking",
            "parking",
            "Pier",
            "Plane",
            "Platform",
            "Public Art",
            "Rental Car Location",
            "Subway",
            "subway_station",
            "Taxi",
            "Taxi Stand",
            "taxi_stand",
            "Toll Booth",
            "Toll Plaza",
            "Train",
            "Train Station",
            "train_station",
            "Tram",
            "transit_station",
            "Transportation Service",
            "Travel & Transport",
            "Tunnel",
        ],
      }

    end

  end
end