[  
   {  
      source_day: 1,
      source_time: "6 p.m.",
      source_index: "1",
      source_group: "Favorite Haunts",
      name: "St. Peter's Episcopal Church Cemetery",
      street_address: "Alachua and Eighth Streets",
      locality: "Amelia Island, Fla.",
      phone: "904-261-7378",
   },
   {  
      source_day: 1,
      source_time: "7:30 p.m.",
      source_index: "2",
      source_group: "Dinner Down Under",
      name: "The Down Under",
      street_address: "4883 Otis Trail, Fernandina Beach",
      locality: "Amelia Island, Fla.",
      phone: "904-277-1557",
   },
   {  
      source_day: 2,
      source_time: "9 a.m.",
      source_index: "3",
      source_group: "To Market",
      name: "Central Park",
      street_address: "11th and Centre Streets",
      locality: "Amelia Island, Fla.",
      phone: "9 a.m. to 2 p.m.",
   },
   {  
      source_day: 2,
      source_time: "10 a.m.",
      source_index: "4",
      source_group: "White Sand Ride",
      name: "Kelly Seahorse Ranch",
      street_address: "7500 First Coast Highway",
      locality: "Amelia Island, Fla.",
      phone: "904-491-5166",
   },
   {  
      source_day: 2,
      source_time: "11:30 a.m.",
      source_index: "5",
      source_group: "Hit the Beach",
      name: "Gourmet Gourmet",
      street_address: "1408 Lewis Street",
      locality: "Amelia Island, Fla.",
      phone: "904-261-8973",
   },
   {  
      source_day: 2,
      source_time: "3 p.m.",
      source_index: "6",
      source_group: "Park and Pier",
      name: "Fort Clinch State Park",
      street_address: "2601 Atlantic Avenue",
      locality: "Amelia Island, Fla.",
      phone: "904-277-7274",
   },
   {  
      source_day: 2,
      source_time: "6 p.m.",
      source_index: "7",
      source_group: "Cocktails on the Porch",
      name: "Brett's Waterway Café",
      street_address: "1 South Front Street",
      locality: "Amelia Island, Fla.",
      phone: "904-261-2660",
   },
   {  
      source_day: 2,
      source_time: "7:30 p.m.",
      source_index: "8",
      source_group: "Victorian Dining",
      name: "Beech Street Grill",
      street_address: "801 Beech Street",
      locality: "Amelia Island, Fla.",
      phone: "904-277-3662",
   },
   {  
      source_day: 3,
      source_time: "9 a.m.",
      source_index: "10",
      source_group: "Work Out the Kinks",
      name: "",
      street_address: "60 Amelia Village Circle",
      locality: "Amelia Island, Fla.",
      phone: "877-843-7722",
   },
   {  
      source_day: 3,
      source_time: "11 a.m.",
      source_index: "11",
      source_group: "Boardinghouse Brunch",
      name: "Florida House Inn",
      street_address: "22 South Third Street",
      locality: "Amelia Island, Fla.",
      phone: "904-261-3300",
   },
   {  
      source_group: "Destination Details",
      name: "Amelia Island Plantation",
      street_address: "6800 First Coast Highway",
      locality: "Amelia Island, Fla.",
      phone: "888-261-6161",
   },
   {  
      source_group: "Destination Details",
      name: "The Ritz-Carlton, Amelia Island",
      street_address: "4750 Amelia Island Parkway",
      locality: "Amelia Island, Fla.",
      phone: "904-277-1100.",
   },
   {  
      source_group: "Destination Details",
      name: "Fairbanks House",
      street_address: "227 South Seventh Street",
      locality: "Amelia Island, Fla.",
      phone: "888-891-9882",
   }
]